DATALOADER:
  NUM_WORKERS: 4
  TRAIN_X:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 30
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 6
  TEST:
    BATCH_SIZE: 30

OPTIM:
  NAME: 'sgd'
  LR: 0.002
  MAX_EPOCH: 40
  LR_SCHEDULER: 'cosine'

TRAIN:
  PRINT_FREQ: 100

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ['random_flip', 'randaugment_fixmatch', 'normalize', 'cutout']
    EMA_ALPHA: 0.999
  DACNET:
    LOSS_TYPE: 'L1'
    WEIGHT_D: 0.3  # domain attention consisitency loss weight
    WEIGHT_CON: 0.1  # class compactness loss weight
