DATALOADER:
  NUM_WORKERS: 2
  TRAIN_X:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 48
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 100

OPTIM:
  NAME: 'adam'
  LR: 0.00005
  MAX_EPOCH: 100
  LR_SCHEDULER: 'cosine'

TRAINER:
  FIXMATCH:
     STRONG_TRANSFORMS: ['random_flip', 'randaugment_fixmatch', 'normalize', 'cutout']
     EMA_ALPHA: 0.999
  DACNET:
    LOSS_TYPE: 'L1'
    WEIGHT_D: 0.3  # domain attention loss weight
    WEIGHT_CON: 0.1  # class compactness loss weight

